### ISSUE TITLE
Executing a parsed query documents raises an error

### ISSUE THREAD

**Issue by jturkel** [Shopify/graphql-metrics#27]
Invoking `GraphQL::Schema.execute` with an already parsed GraphQL document results in an error like this:

```
     TypeError:
       nil can't be coerced into Float
     # /Users/jturkel/.rvm/gems/ruby-2.5.3@bugs/gems/graphql-metrics-4.0.2/lib/graphql/metrics/instrumentation.rb:39:in `-'
     # /Users/jturkel/.rvm/gems/ruby-2.5.3@bugs/gems/graphql-metrics-4.0.2/lib/graphql/metrics/instrumentation.rb:39:in `after_query'
     # /Users/jturkel/.rvm/gems/ruby-2.5.3@bugs/gems/graphql-1.10.14/lib/graphql/execution/instrumentation.rb:82:in `public_send'
     # /Users/jturkel/.rvm/gems/ruby-2.5.3@bugs/gems/graphql-1.10.14/lib/graphql/execution/instrumentation.rb:82:in `block in call_after_hooks'
     # ...
```

It looks like the problem is `GraphQL::Metrics::Tracer` relies on the `lex` trace event to capture the query start time resulting in an unexpected `nil` in `GraphQL::Metrics::Instrumentation#after_query`. Perhaps in this scenario `GraphQL::Metrics::Tracer` should use the `validate` trace hook to set the query start time? I'd be happy to put up a PR after nailing down the general approach.

Here's a reproducible test case:

```ruby
require 'bundler/inline'

gemfile(true) do
  source 'https://rubygems.org'
  gem 'graphql', '1.10.14'
  gem 'graphql-metrics', '4.0.2'
  gem 'activesupport'
  gem 'rspec'
end

require 'active_support/all'
require 'rspec/autorun'

class QueryType < GraphQL::Schema::Object
  field :ping, String, null: false

  def ping
    'ok'
  end
end

class SimpleAnalyzer < GraphQL::Metrics::Analyzer
  def query_extracted(metrics)
    # no-op
  end

  def field_extracted(metrics)
    # no-op
  end

  def argument_extracted(metrics)
    # no-op
  end
end

class TestSchema < GraphQL::Schema
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  query_analyzer SimpleAnalyzer
  instrument :query, GraphQL::Metrics::Instrumentation.new
  tracer GraphQL::Metrics::Tracer.new

  query QueryType
end

describe 'GraphQL::Schema#execute' do
  it 'accepts query documents' do
    query = <<~GRAPHQL
      query {
        ping
      }
    GRAPHQL

    query_document = GraphQL.parse(query)

    expected = {
      data: {
        ping: 'ok'
      }
    }

    result = TestSchema.execute(document: query_document)
    expect(result.to_json).to eq(expected.to_json)
  end
end
```

**Comment by swalkinshaw** [comment]
> Perhaps in this scenario GraphQL::Metrics::Tracer should use the validate trace hook to set the query start time?

That seems like a good compromise. Just check if the start time has already been set or not within `validate`, if not, set it.

**Comment by chrisbutcher** [comment]
+1 that sounds good!
